services:
  nginx:
    image: ghcr.io/${GITHUB_REPO}/frontend:${GITHUB_SHA}
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - ${PROJECT_PATH}/frontend/.env.production
    volumes:
      - ${EXTERNAL_STATIC_MEDIA_PATH}:${INTERNAL_STATIC_MEDIA_PATH}
    # hostname: nginx
    networks:
      - appnet

  # change db code to contact postgres CONTAINER, not localhost!
  # db:5432
  # postgres://DB_USER:DB_PASS@db:5432/DB_NAME
  db:
    image: postgres:15
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    # hostname: ${DB_HOST}
    networks:
      - appnet

  backend:
    container_name: ${API_HOST}
    image: ghcr.io/${GITHUB_REPO}/backend:${GITHUB_SHA}
    # command: tail -f 
    ports:
      - "${API_PORT}:5000"
    env_file:
      - ${PROJECT_PATH}/backend/.env.production

    volumes:
      - ${EXTERNAL_STATIC_MEDIA_PATH}:${INTERNAL_STATIC_MEDIA_PATH}
    
    # hostname: ${API_HOST}
    networks:
      - appnet


  graphite:
    image: graphiteapp/graphite-statsd
    container_name:  ${GRAPHITE_HOST}
    restart: always
    ports:
      # - "${GRAFANA_PORT_WEB_UI}:3000"       # Grafana Web UI
      # - "${GRAPHITE_PORT_WEB_UI}:80"       # Graphite Web UI
      - "${GRAPHITE_PORT_INGEST}:8125/udp" # StatsD UDP ingestion
      - "${GRAPHITE_PORT_ADMIN}:8126"   # StatsD admin
      - "${GRAPHITE_PORT_CARBON}:2003"   # StatsD admin
    volumes:
      - graphite_data:/opt/graphite/storage
    # hostname: ${GRAPHITE_HOST}
    networks:
      - appnet

  
volumes:
  postgres_data:
  graphite_data:

networks:
  appnet:

