services:
  nginx:
    image: ghcr.io/${GITHUB_REPO}/frontend:${GITHUB_SHA}
    container_name: nginx
    ports:
      - "80:80"
    env_file: 
      - ${PROJECT_PATH}/frontend/.env.production
    volumes:
      - ${EXTERNAL_STATIC_MEDIA_PATH}:${INTERNAL_STATIC_MEDIA_PATH}
    # hostname: nginx
    networks:
      - appnet

  # change db code to contact postgres CONTAINER, not localhost!
  # db:5432
  # postgres://DB_USER:DB_PASS@db:5432/DB_NAME
  db:
    image: postgres:15
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    # hostname: ${DB_HOST}
    networks:
      - appnet

  backend:
    container_name: ${API_HOST}
    image: ghcr.io/${GITHUB_REPO}/backend:${GITHUB_SHA}
    # command: tail -f 
    ports:
      - "${API_PORT}:5000"
    env_file:
      - ${PROJECT_PATH}/backend/.env.production

    volumes:
      - ${EXTERNAL_STATIC_MEDIA_PATH}:${INTERNAL_STATIC_MEDIA_PATH}
      - backend_logs:${LOGS_FILE_PATH}
    
    # hostname: ${API_HOST}
    networks:
      - appnet


  graphite:
    image: graphiteapp/graphite-statsd
    container_name:  ${GRAPHITE_HOST}
    restart: always
    ports:
      - "${GRAPHITE_PORT_INGEST}:8125/udp" # StatsD UDP ingestion
      - "${GRAPHITE_PORT_ADMIN}:8126"   # StatsD admin
      - "${GRAPHITE_PORT_CARBON}:2003"   # StatsD admin
    volumes:
      - graphite_data:/opt/graphite/storage
      - ./graphite/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py:ro
    networks:
      - appnet

  promtail:
    image: grafana/promtail:latest
    container_name:  ${PROMTAIL_HOST}
    volumes:
      - backend_logs:/var/log/backend:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - appnet

  loki:
    image: grafana/loki
    container_name:  ${LOKI_HOST}
    restart: always
    volumes:
      - loki_data:/loki
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    container_name:  ${GRAFANA_HOST}
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    networks:
      - appnet
  
volumes:
  backend_logs:
  postgres_data:
  graphite_data:
  loki_data:
  grafana_data:

networks:
  appnet:

