# cicd.yaml

name: Deploy

on:
        push:
                branches:
                        - main
                        - refactor
                        - dockerize
                        
permissions:
        contents: read
        packages: write
        
jobs:
        lint-ci-build-upload:
                environment: prod
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout repo
                          uses: actions/checkout@v4

                        - name: Install lint
                          run: |
                                npm install --only=dev

                        - name: Lint project
                          run: npm run lint

                        - name: Build frontend Docker image
                          run: |
                                set -euo pipefail
                                
                                docker build \
                                --build-arg REACT_APP_API_URL=${{ vars.PUBLIC_API_DOMAIN }} \
                                --build-arg REACT_APP_FEATURE_FLAG=${{ vars.REACT_APP_FEATURE_FLAG }} \
                                --build-arg REACT_APP_MAX_FILES_PER_UPLOAD=${{ vars.REACT_APP_MAX_FILES_PER_UPLOAD }} \
                                -t ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} \
                                -f infra/docker/frontend/Dockerfile .

                        - name: Build backend Docker image
                          run: |
                                set -euo pipefail

                                docker build \
                                -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} \
                                -f infra/docker/backend/Dockerfile .

                        - name: Push frontend Docker image
                          run: |
                                set -euo pipefail
                                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                                docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

                        - name: Push backend Docker image
                          run: |
                                set -euo pipefail
                                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                                docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

        prep-download-deploy:
                runs-on: ubuntu-latest
                environment: prod
                needs: lint-ci-build-upload
                steps:

                        - name: Ensure all folders & files & dependencies exist
                          uses: appleboy/ssh-action@v0.1.10
                          with:
                                host: ${{ secrets.TARGET_HOST }}
                                username: ${{ secrets.TARGET_USER }}
                                key: ${{ secrets.SSH_PRIVATE_KEY }}
                                port: ${{ secrets.TARGET_PORT }}

                                proxy_host: ${{ secrets.GATEWAY_HOST }}
                                proxy_port: ${{ secrets.GATEWAY_PORT }}
                                proxy_username: ${{ secrets.GATEWAY_USER }}
                                proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
                                script: |
                                        echo "----------------------------------------------" 
                                        set -euo pipefail
                                        echo "Creating volume folders..."  
                                        
                                        export EXTERNAL_STATIC_MEDIA_PATH="/var/www/${{ github.event.repository.name }}/uploads"
                                        export DOWN_SCALE_IMAGE_FOLDER_NAME="${{ vars.DOWN_SCALE_IMAGE_FOLDER_NAME }}"
                                        export FULL_SCALE_IMAGE_FOLDER_NAME="${{ vars.FULL_SCALE_IMAGE_FOLDER_NAME}}"
                                        export ORIGINAL_SCALE_IMAGE_FOLDER_NAME="${{ vars.ORIGINAL_SCALE_IMAGE_FOLDER_NAME }}"
                                        export TEMP_SCALE_IMAGE_FOLDER_NAME="${{ vars.TEMP_SCALE_IMAGE_FOLDER_NAME }}"   

                                        # volumes
                                        sudo mkdir -p "${EXTERNAL_STATIC_MEDIA_PATH}"
                                        sudo mkdir -p "${EXTERNAL_STATIC_MEDIA_PATH}/${DOWN_SCALE_IMAGE_FOLDER_NAME}"
                                        sudo mkdir -p "${EXTERNAL_STATIC_MEDIA_PATH}/${FULL_SCALE_IMAGE_FOLDER_NAME}"
                                        sudo mkdir -p "${EXTERNAL_STATIC_MEDIA_PATH}/${ORIGINAL_SCALE_IMAGE_FOLDER_NAME}"
                                        sudo mkdir -p "${EXTERNAL_STATIC_MEDIA_PATH}/${TEMP_SCALE_IMAGE_FOLDER_NAME}"

                                        sudo mkdir -p "/srv/${{ github.event.repository.name }}"
                                        sudo chown -R "$USER:$USER" "/var/www/${{ github.event.repository.name }}"
                                        sudo chown -R "$USER:$USER" "/srv/${{ github.event.repository.name }}"

                                        echo "External media folders generated..."

                                        # repo
                                        echo "----------------------------------------------" 
                                        echo "Pulling latest code..."   
                                        export REPO_OWNER="${{ github.repository_owner }}"
                                        export GITHUB_ACTOR="${{github.actor}}"
                                        export ACCOUNT_TOKEN="${{ secrets.ACCOUNT_TOKEN }}"
                                        export PROJECT_PATH="/srv/${{ github.event.repository.name }}"
                                        export BRANCH="${{ github.ref_name }}"
                                        

                                        if [ ! -d "${PROJECT_PATH}/.git" ]; then
                                        echo "Cloning repo..."
                                        git clone --branch "$BRANCH" "https://${GITHUB_ACTOR}:${ACCOUNT_TOKEN}@github.com/${REPO_OWNER}/${REPO_NAME}.git" "$PROJECT_PATH"
                                        else
                                        echo "Updating repo..."
                                        cd "$PROJECT_PATH"
                                        git fetch origin "$BRANCH"
                                        git reset --hard "origin/$BRANCH"
                                        fi

                                        echo "----------------------------------------------" 
                                        export PUBLIC_API_DOMAIN=${{ vars.PUBLIC_API_DOMAIN }}
                                        export API_PORT="${{ vars.API_PORT }}"
                                        export INTERNAL_STATIC_MEDIA_PATH="${{ vars.INTERNAL_STATIC_MEDIA_PATH }}"
                                        : "${INTERNAL_STATIC_MEDIA_PATH:=/usr/src/app/uploads}"

                                        echo "Generating nginx config..."  
                                        sudo cat > ${PROJECT_PATH}/infra/nginx/frontend.conf <<EOF
                                        server {
                                                listen 80;
                                                listen [::]:80;
                                                client_max_body_size 50M;

                                                server_name _;

                                                # Serve React frontend
                                                location / {
                                                        root /usr/share/nginx/html;
                                                        index index.html;
                                                        try_files \$uri /index.html;
                                                }

                                                # Forward API requests to backend container
                                                location /api/ {
                                                        proxy_pass http://127.0.0.1:${API_PORT};
                                                        proxy_set_header Host \$host;
                                                        proxy_set_header X-Real-IP \$remote_addr;
                                                        proxy_request_buffering off;
                                                        proxy_read_timeout 300;
                                                }

                                                # Serve media uploads
                                                location /media/ {
                                                        alias ${INTERNAL_STATIC_MEDIA_PATH}/;
                                                        autoindex off;
                                                }
                                        }
                                        EOF
                                        echo "Generated nginx config."  
                                        echo "----------------------------------------------" 

                                        echo "Installing Docker..."

                                        if ! command -v docker >/dev/null 2>&1; then
                                                echo "Docker not found, installing..."
                                                sudo apt-get update -y
                                                sudo apt-get install -y docker.io docker-compose-v2
                                                sudo systemctl enable --now docker
                                        else
                                                echo "Docker already installed: $(docker --version)"
                                        fi

                                        if ! sudo docker compose version >/dev/null 2>&1; then
                                                echo "Docker Compose not found, installing..."
        
                                                sudo apt-get update -y
                                                sudo apt-get install -y docker-compose-v2
                                        fi

                                        sudo docker compose version
                                        echo "Docker installed."  
                                        echo "----------------------------------------------" 

                        - name: Download builds
                          uses: appleboy/ssh-action@v0.1.10
                          with:
                                  host: ${{ secrets.TARGET_HOST }}
                                  username: ${{ secrets.TARGET_USER }}
                                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                                  port: ${{ secrets.TARGET_PORT }}

                                  proxy_host: ${{ secrets.GATEWAY_HOST }}
                                  proxy_port: ${{ secrets.GATEWAY_PORT }}
                                  proxy_username: ${{ secrets.GATEWAY_USER }}
                                  proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
                                  script: |
                                         set -euo pipefail
                                          echo "----------------------------------------------"
                                          echo "Downloading docker images..."
                                          echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
                                          sudo docker pull ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
                                          sudo docker pull ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

                        - name: Deploy
                          uses: appleboy/ssh-action@v0.1.10
                          with:
                                  host: ${{ secrets.TARGET_HOST }}
                                  username: ${{ secrets.TARGET_USER }}
                                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                                  port: ${{ secrets.TARGET_PORT }}

                                  proxy_host: ${{ secrets.GATEWAY_HOST }}
                                  proxy_port: ${{ secrets.GATEWAY_PORT }}
                                  proxy_username: ${{ secrets.GATEWAY_USER }}
                                  proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
                                  script: |
                                          set -euo pipefail
                                          echo "----------------------------------------------"
                                          echo "Exporting environment variables..."

                                          export PROJECT_PATH=/srv/${{ github.event.repository.name }}
                                          export BACKEND_ENV_PATH="${PROJECT_PATH}/backend/.env.production"
                                          export FRONTEND_ENV_PATH="${PROJECT_PATH}/frontend/.env.production"
                                          export DB_USER="${{ secrets.DB_USER }}"
                                          export DB_PASS="${{ secrets.DB_PASS }}"
                                          export DB_NAME="${{ vars.DB_NAME }}"
                                          export DB_HOST="${{ vars.DB_HOST }}"
                                          export DB_PORT="${{ vars.DB_PORT }}"
                                          export API_PORT="${{ vars.API_PORT }}"
                                          
                                          # volumes will map uploads to the external media path
                                          export EXTERNAL_STATIC_MEDIA_PATH="/var/www/${{ github.event.repository.name }}/uploads"
                                          export INTERNAL_STATIC_MEDIA_PATH="${{ vars.INTERNAL_STATIC_MEDIA_PATH }}"
                                          : "${INTERNAL_STATIC_MEDIA_PATH:=/usr/src/app/uploads}"


                                          export REACT_APP_FEATURE_FLAG="${{ vars.REACT_APP_FEATURE_FLAG }}"
                                          export REACT_APP_MAX_FILES_PER_UPLOAD="${{ vars.REACT_APP_MAX_FILES_PER_UPLOAD }}"
                                          echo "Environment variables exported.\n\n"
                                          


                                          echo "----------------------------------------------"
                                          echo "Generating .env files..."
                                          sudo mkdir -p "$(dirname "$BACKEND_ENV_PATH")"
                                          sudo touch "$BACKEND_ENV_PATH"
                                          sudo mkdir -p "$(dirname "$FRONTEND_ENV_PATH")"
                                          sudo touch "$FRONTEND_ENV_PATH"


                                          sudo cat > ${BACKEND_ENV_PATH} <<EOF
                                          API_PORT=$API_PORT
                                          DB_USER=$DB_USER
                                          DB_PASS=$DB_PASS
                                          DB_NAME=$DB_NAME
                                          DB_HOST=$DB_HOST
                                          DB_PORT=$DB_PORT
                                          PUBLIC_API_DOMAIN=${{ vars.PUBLIC_API_DOMAIN }}
                                          BASE_MEDIA_PATH=$INTERNAL_STATIC_MEDIA_PATH
                                          DOWN_SCALE_IMAGE_FOLDER_NAME="${{ vars.DOWN_SCALE_IMAGE_FOLDER_NAME }}"
                                          FULL_SCALE_IMAGE_FOLDER_NAME="${{ vars.FULL_SCALE_IMAGE_FOLDER_NAME }}"
                                          ORIGINAL_SCALE_IMAGE_FOLDER_NAME="${{ vars.ORIGINAL_SCALE_IMAGE_FOLDER_NAME }}"
                                          TEMP_SCALE_IMAGE_FOLDER_NAME="${{ vars.TEMP_SCALE_IMAGE_FOLDER_NAME }}"
                                          EOF


                                          sudo cat > ${FRONTEND_ENV_PATH} <<EOF
                                          REACT_APP_API_URL=${{ vars.PUBLIC_API_DOMAIN }}
                                          REACT_APP_FEATURE_FLAG=$REACT_APP_FEATURE_FLAG
                                          REACT_APP_MAX_FILES_PER_UPLOAD=$REACT_APP_MAX_FILES_PER_UPLOAD
                                          EOF
                                          echo "Generated .env files...\n\n"


                                          echo "----------------------------------------------"
                                          echo "Deploying Docker Containers..."
                                          sudo docker compose -f "${PROJECT_PATH}/infra/docker/docker-compose.yml" up -d

                                          echo "Running migrations..."
                                          sudo docker compose exec backend npm run migrate:up

                                          echo "Containers deployed...\n\n"
                                          echo "----------------------------------------------"
